#!/bin/bash

# crontab -e 
# 0 4 * * 0 ~/scripts/02

if [ ! -f /var/log/update_script.log ]
then
	sudo touch /var/log/update_script.log;
	sudo chmod 666 /var/log/update_script.log;
fi
sudo apt-get update > /var/log/update_script.log && sudo apt-get upgrade -y > /var/log/update_script.log
